# -*- coding: utf-8 -*-
"""count zeroes using recursion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AiCza4PKEwRLF-DncH_qOpFk0Pcw-tW
"""

def count_zeroes(n):
    if n == 0:
        return 1

    if n < 10:
        return 0

    return (1 if n % 10 == 0 else 0) + count_zeroes(n // 10)

n = int(input("Enter an integer: "))
print("Number of zeroes:", count_zeroes(n))