# -*- coding: utf-8 -*-
"""count odd digits in int

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EphMxhfggMcmrq7E0U_j2NH_p9PAUnYn
"""

def count_odd_digits(n):
    if n == 0:
        return 0
    else:
        last_digit = n % 10
        if last_digit % 2 != 0:
            return 1 + count_odd_digits(n // 10)
        else:
            return count_odd_digits(n // 10)

print(count_odd_digits(12345678))