# -*- coding: utf-8 -*-
"""count num of digits in int using recurison

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HJn_uiQqQPsDxUAO9cLZ0i9rR82OPnSZ
"""

def count_digits(n):
    if n < 10 and n >= 0:
        return 1
    else:
        return 1 + count_digits(n // 10)

print(count_digits(12345))