# -*- coding: utf-8 -*-
"""count digits in string using recursion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EphMxhfggMcmrq7E0U_j2NH_p9PAUnYn
"""

def count_digits_in_string(s):
    if s == "":
        return 0
    elif s[0].isdigit():
        return 1 + count_digits_in_string(s[1:])
    else:
        return count_digits_in_string(s[1:])

print(count_digits_in_string("nidhi12123dev"))