# -*- coding: utf-8 -*-
"""example 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UGced4B9QMRQzGGtpiQCuWe9Y4K463Hn
"""

def fibonacci(n):
# Base case
 if n < 1:
  return -1
 elif n==1:
  return 0
 elif n==2:
  return 1
# Recursive case (binary recursion)
 else:
  return fibonacci(n-1) + fibonacci(n-2)
# Example usage
n = 5 # Change this value to test other positions
print(f"Fibonacci number at position {n} is {fibonacci(n)}")

