# -*- coding: utf-8 -*-
"""example 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UGced4B9QMRQzGGtpiQCuWe9Y4K463Hn
"""

def factorial(num):
 if num == 0:
  return 1
 else:
  return num*factorial (num-1)
n = int(input("Enter any number: "))
fact = factorial(n)
print("Factorial output:",fact)

