# -*- coding: utf-8 -*-
"""example 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UGced4B9QMRQzGGtpiQCuWe9Y4K463Hn
"""

def power(a,b):
 if b == 0:
  return 1
 else:
    return a*power (a,b-1)
num = int(input("Enter any number:"))
exp = int(input("Enter exponent:"))
result = power(num,exp)
print("Result:",result)

