# -*- coding: utf-8 -*-
"""fibonnaci using mutual recursion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Q1PcXEDX438DTxzbIRgVt4YPGODYwcj
"""

def even_fib(n):
    if n == 0:
        return 0
    return odd_fib(n - 1)

def odd_fib(n):
    if n == 0:
        return 1
    return even_fib(n - 1) + odd_fib(n - 1)

def fibonacci_series(n):
    return [even_fib(i) if i % 2 == 0 else odd_fib(i) for i in range(n)]

# Example usage:
n = int(input("Enter the number of terms: "))
print("Fibonacci series:", fibonacci_series(n))

