# -*- coding: utf-8 -*-
"""gcd using recursion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x7j17vN9P-fisW_rD49fInm25vhq4jz-
"""

def gcd(a, b):
    if b == 0:
        return a
    return gcd(b, a % b)

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("GCD:", gcd(a, b))

