# -*- coding: utf-8 -*-
"""hanoi tower

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JO4D5dkq5uj4bIpmMtZ84ZjNRd-R3Gyr
"""

def tower_of_hanoi(n, source, auxiliary, target):
    if n == 1:
        print(f"Move disk 1 from {source} to {target}")
        return

    tower_of_hanoi(n - 1, source, target, auxiliary)

    print(f"Move disk {n} from {source} to {target}")

    tower_of_hanoi(n - 1, auxiliary, source, target)

n = int(input("Enter the number of disks: "))
tower_of_hanoi(n, 'A', 'B', 'C')

