# -*- coding: utf-8 -*-
"""len of string using recurison

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EphMxhfggMcmrq7E0U_j2NH_p9PAUnYn
"""

def string_length(s):
    if s == "":
        return 0
    else:
        return 1 + string_length(s[1:])

print(string_length("structure"))