# -*- coding: utf-8 -*-
"""sum using recursion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T0Na-V7BfTmZFqc3np3yACmwtdLUtuKd
"""

def sum_of_digits(n):
    if n == 0:
        return 0
    return n % 10 + sum_of_digits(n // 10)

# Example usage:
n = int(input("Enter a number: "))
print("Sum of digits:", sum_of_digits(n))

